services:
  postgres:
    image: postgres
    container_name: uniform_db
    environment:
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - uniform_network

volumes:
  postgres_data:

networks:
  uniform_network: